# Generated by Django 5.1.5 on 2025-02-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('point', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=0)),
                ('tier', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
